#!/bin/bash

export PRECONFIGURED_WIREGUARD_IP_CIDR=10.10.117.0/24
export PRECONFIGURED_HOST_WIREGUARD_CLIENT_NO=002
export CLUSTER_LOAD_BALANCER_END_POINT=10.10.117.2
export PRECONFIGURED_VM_IP_START=192.168.128.1
export PRECONFIGURED_HOST_IP=PRECONFIGURED_VM_IP_START
export PRECONFIGURED_VM_IP_END=192.168.128.200
export PRECONFIGURED_VM_IP_SUBNET=255.255.255.0
export K8S_VERSION=1.33.0
export HAPROXY_STAT_USER=admin
export HAPROXY_STAT_PASSWORD=admin1234

export LOADBALANCER_CONF_DIR="$(pwd)/.loadbalancer"
export HAPROXY_PATH="$LOADBALANCER_CONF_DIR/haproxy.cfg"
export MAIN_ADDRESSES_FILE="$LOADBALANCER_CONF_DIR/main-addresses.txt"
export API_SERVER_PORT=6443
export ETCD_CLIENT_PORT=2379
export ETCD_PEER_PORT=2380

export PODMAN_MACHINE_NAME="podman-machine-default"

export CLUSTER_NAME="my-k8s-cluster"

export KUBEADM_CERT_KEY_PATH=".keys/kubeadm-cert-key.txt"

# to use flannel as the CNI plugin
export POD_NETWORK_CIDR=10.244.0.0/16

echo "Environment variable set: PRECONFIGURED_WIREGUARD_IP_CIDR=$PRECONFIGURED_WIREGUARD_IP_CIDR"
echo "Environment variable set: PRECONFIGURED_HOST_WIREGUARD_CLIENT_NO=$PRECONFIGURED_HOST_WIREGUARD_CLIENT_NO"
echo "Environment variable set: PRECONFIGURED_VM_IP_START=$PRECONFIGURED_VM_IP_START"
echo "Environment variable set: PRECONFIGURED_VM_IP_END=$PRECONFIGURED_VM_IP_END"
echo "Environment variable set: PRECONFIGURED_VM_IP_SUBNEt=$PRECONFIGURED_VM_IP_SUBNET"