#!/bin/bash

export PRECONFIGURED_WIREGUARD_IP_CIDR=10.10.117.0/24
export PRECONFIGURED_WIREGUARD_CHECK_CLIENT_NO=002
export PRECONFIGURED_VM_IP_START=192.168.128.1
export PRECONFIGURED_HOST_IP=PRECONFIGURED_VM_IP_START
export PRECONFIGURED_VM_IP_END=192.168.128.200
export PRECONFIGURED_VM_IP_SUBNET=255.255.255.0
export K8S_VERSION=1.33.0

export PODMAN_MACHINE_NAME="podman-machine-vpn"

export CLUSTER_NAME="my-k8s-cluster"

# to use flannel as the CNI plugin
export POD_NETWORK_CIDR=10.244.0.0/16

echo "Environment variable set: PRECONFIGURED_WIREGUARD_IP_CIDR=$PRECONFIGURED_WIREGUARD_IP_CIDR"
echo "Environment variable set: PRECONFIGURED_WIREGUARD_CHECK_CLIENT_NO=$PRECONFIGURED_WIREGUARD_CHECK_CLIENT_NO"
echo "Environment variable set: PRECONFIGURED_VM_IP_START=$PRECONFIGURED_VM_IP_START"
echo "Environment variable set: PRECONFIGURED_VM_IP_END=$PRECONFIGURED_VM_IP_END"
echo "Environment variable set: PRECONFIGURED_VM_IP_SUBNEt=$PRECONFIGURED_VM_IP_SUBNET"