#!/bin/bash

export PRECONFIGURED_WIREGUARD_IP_CIDR=10.10.117.0/24
export PRECONFIGURED_VM_IP_START=192.168.128.1
export PRECONFIGURED_VM_IP_END=192.168.128.200
export PRECONFIGURED_VM_IP_SUBNET=255.255.255.0

echo "Environment variable set: PRECONFIGURED_WIREGUARD_IP_CIDR=$PRECONFIGURED_WIREGUARD_IP_CIDR"
echo "Environment variable set: PRECONFIGURED_VM_IP_START=$PRECONFIGURED_VM_IP_START"
echo "Environment variable set: PRECONFIGURED_VM_IP_END=$PRECONFIGURED_VM_IP_END"
echo "Environment variable set: PRECONFIGURED_VM_IP_SUBNEt=$PRECONFIGURED_VM_IP_SUBNET"